#!/usr/bin/env python3
"""Advance finished pipeline stages without a model.

The Dispatcher is a `process` agent: the server routes every stage-completion
wake to it instead of the Coordinator (`stageDispatcherIdFor`). Those wakes were
nearly nine in ten Coordinator runs, and most of them resolved through the
mechanical rows of the Coordinator's stage table at the cost of re-reading its
whole instruction set. This script runs those rows directly:

  Worker done, committed, clean tree      -> Review subtask
  Reviewer done, needs-build              -> Verify subtask
  Reviewer done, data-only, data touched  -> Verify subtask
  rebase finished, merge-tree clean       -> close it, re-Verify the parent
                                             (or resume the Review it held)
  stage blocked on a merge conflict       -> Rebase subtask, Worker slots allowing
  held Verify, capacity free              -> dispatch it
  Verify whose landed head the PR carries -> close it (or the PR merged)
  `Held: until <id> merges|opens its PR`  -> back to backlog once it has
  `Held: waiting on <id>`, <id> closed     -> back to backlog
  its own routine fire, sweep finished      -> close the routine's issue

Everything else that is waiting on the Coordinator -- a dirty tree, no commits,
a chain, a finished rebase, an unlabeled task -- is handed off in ONE wake, and
only when its state changed since the last hand-off. The list itself is written
to HANDOFF_FILE for the Coordinator to read: a wake payload naming an issue
would make the run task-scoped and take that task's execution lock.
That wake also asks for a slot refill when Worker slots are free and backlog
holds work, because promotion needs the contention and hold rules a script
should not guess at.

Wakes coalesce per agent, so a run cannot trust its payload to name every task
that advanced. It sweeps the board instead; every action is idempotent (the
server's `(parentId, dedupeKey)` index makes a duplicate create return the
existing subtask).

    dispatch.py            sweep and act
    dispatch.py --dry-run  print the actions, write nothing
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
STATE_DIR = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "paperclip-dispatcher"
HANDOFF_FILE = STATE_DIR / "handoff.json"
#: Hold release reads every held task's comments; once per window is plenty.
HOLD_SCAN_INTERVAL = float(os.environ.get("DISPATCHER_HOLD_SCAN_SECONDS", 300))
#: A refill wake the Coordinator just answered needs no repeat inside this window.
REFILL_INTERVAL = float(os.environ.get("DISPATCHER_REFILL_SECONDS", 300))

STAGE_KEYS = {"review": "review", "verify": "verify", "ci-fix": "verify", "rebase": "rebase"}
STAGE_PREFIXES = {"Review:": "review", "Verify:": "verify", "ci-fix:": "verify", "Rebase ": "rebase"}
OPEN = {"backlog", "todo", "in_progress", "in_review", "blocked"}
DATA_PATH = re.compile(r"^assets/(data|locales)/")
#: Paths cargo builds or tests: Rust, its manifests, and the data unit tests load.
CARGO_PATH = re.compile(r"(\.rs$|(^|/)Cargo\.(toml|lock)$|^assets/(data|locales)/)")
#: Most tasks carry their pipeline label in the body, not as an issue label.
LABEL_LINE = re.compile(r"(?im)^\W*label\W*:\W*(needs-build|data-only)\b")
#: A hold names its own release condition. `merges`: the task builds on the
#: blocker's code, which is not on main until it lands. `opens its PR`: the
#: blocker is being written on the same files (or is the previous link of a
#: same-shaped chain), and stops contending once it is finished.
HELD_UNTIL = re.compile(r"^Held: until ([A-Z]+-\d+) (merges|opens its PR)\b")
LEGACY_HOLD = "Held: waiting on "
LEGACY_HELD = re.compile(r"^Held: waiting on ([A-Z]+-\d+)\b")
#: Regenerated by the Architect's schema step, so never a reason to rebase.
SCHEMA_PATH = re.compile(r"^assets/schemas/")
#: Rebases one parent may consume. A finished rebase that conflicts again means
#: `main` moved on the same files; past this many, the file is too hot for a
#: Worker to win the race and the merge is the operator's.
MAX_REBASES = int(os.environ.get("DISPATCHER_MAX_REBASES", 3))
HELD_VERIFY = "Intended assignee: Architect (held"
VERIFY_DIR = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "paperclip-verify"


# --------------------------------------------------------------------------- decisions


@dataclass(frozen=True)
class GitState:
    exists: bool
    dirty: bool = False
    ahead: int = 0
    head: str = ""
    changed: tuple[str, ...] = ()
    merges_clean: bool = False
    #: Conflicting paths against origin/main; empty when it merges clean.
    conflicts: tuple[str, ...] = ()
    #: A path origin/main deleted that the branch still modifies, with no module
    #: directory replacing it: no second version to reconcile, so the task is
    #: re-filed, not rebased.
    deleted_on_main: bool = False
    #: Deleted paths origin/main split into a module directory (`x.rs` -> `x/`).
    #: The branch's hunks have a home there, so a Worker ports them.
    split_on_main: tuple[str, ...] = ()


@dataclass(frozen=True)
class Decision:
    kind: str  # "review" | "verify" | "reverify" | "resume-review" | "close-rebase" | "rebase" | "handoff" | "skip"
    reason: str


def stage_of(child: dict) -> str | None:
    key = STAGE_KEYS.get(child.get("dedupeKey") or "")
    if key:
        return key
    for prefix, stage in STAGE_PREFIXES.items():
        if child["title"].startswith(prefix):
            return stage
    return None


def label_names(issue: dict) -> set[str]:
    return {label["name"] for label in issue.get("labels") or []}


def pipeline_label(issue: dict) -> str | None:
    """`needs-build` / `data-only` from the issue's labels, else its `Label:` line."""
    found = label_names(issue) & {"needs-build", "data-only"}
    if found:
        return "needs-build" if "needs-build" in found else "data-only"
    m = LABEL_LINE.search(issue.get("description") or "")
    return m.group(1).lower() if m else None


def finished_rebase(child: dict) -> bool:
    # A Worker never marks its own run done: a finished rebase parks at `in_review`.
    return stage_of(child) == "rebase" and child["status"] == "in_review"


def unconsumed_rebase(stages: list[tuple[str, dict]]) -> dict | None:
    """The newest rebase, if it finished and nothing has run on its head yet.

    Either still parked at `in_review`, or closed `done` by hand while the stage
    it replaced is still `blocked` -- closing it never dispatched that stage again.
    """
    if not stages or stages[-1][0] != "rebase":
        return None
    last = stages[-1][1]
    if finished_rebase(last) or (last["status"] == "done" and superseded(stages)):
        return last
    return None


def ordered_stages(children: list[dict]) -> list[tuple[str, dict]]:
    return sorted(
        ((stage_of(c), c) for c in children if stage_of(c)),
        key=lambda pair: pair[1]["createdAt"],
    )


def superseded(stages: list[tuple[str, dict]]) -> set[str]:
    """Ids of `blocked` stages a later rebase replaced.

    A Verify or Review blocks on a conflict and stays `blocked` while the rebase
    that answers it runs; once the rebase is clean, that stage describes a
    branch that no longer exists.
    """
    last = max((i for i, (stage, _) in enumerate(stages) if stage == "rebase"), default=-1)
    return {c["id"] for stage, c in stages[:last] if stage != "rebase" and c["status"] == "blocked"}


def live_stage(stages: list[tuple[str, dict]]) -> bool:
    """Whether a stage is still running.

    `blocked` is parked, not running. Counting it as live made every finished
    rebase look like it still waited on the Verify it replaced, so none was
    ever closed, and every conflict-blocked Verify hid its parent from the
    rebase dispatch: the branches sat until `main` moved past them again.
    """
    return any(c["status"] in OPEN - {"blocked"} and not finished_rebase(c) for _, c in stages)


def rebases_used(stages: list[tuple[str, dict]]) -> int:
    return sum(1 for stage, c in stages if stage == "rebase" and c["status"] != "cancelled")


def rebase_paths(git: GitState) -> tuple[str, ...]:
    return tuple(p for p in git.conflicts if not SCHEMA_PATH.match(p))


def needs_rebase(parent: dict, stages: list[tuple[str, dict]], git: GitState) -> Decision | None:
    """A rebase for a parent whose last stage stopped on a merge conflict, else None.

    Only an `in_review` parent: a `blocked` one carries someone's hold, and a
    rebase would be wasted on work that hold may cancel.
    """
    if parent["status"] != "in_review" or not stages:
        return None
    stage, last = stages[-1]
    if not ((stage in ("verify", "review") and last["status"] == "blocked") or unconsumed_rebase(stages)):
        return None
    if not git.exists or git.dirty or git.ahead == 0 or git.merges_clean:
        return None
    if git.deleted_on_main:
        return None  # modify/delete: re-filed against the new layout, not rebased
    paths = rebase_paths(git)
    if not paths:
        return None  # schemas only: regenerated, not merged
    if rebases_used(stages) >= MAX_REBASES:
        return None
    return Decision("rebase", ", ".join(paths))


def decide(parent: dict, children: list[dict], git: GitState, pr_head: str | None = None) -> Decision:
    """One parent -> what its next stage is.

    Pure, so the signal table is testable without an API or a worktree.
    """
    stages = ordered_stages(children)
    if parent["status"] in ("done", "cancelled"):
        return Decision("skip", f"parent is {parent['status']}")
    if live_stage(stages):
        return Decision("skip", "a stage is still open")
    if not git.exists:
        return Decision("handoff", "no worktree")

    if unconsumed_rebase(stages):
        # The rebase invalidated whatever verify ran before it, so the next
        # stage is a fresh one -- but only once the conflict is really gone.
        if parent["status"] != "in_review":
            return Decision("handoff", f"rebase finished on a {parent['status']} parent")
        if git.dirty or not git.merges_clean:
            again = needs_rebase(parent, stages, git)
            if again:
                return again  # `main` moved on the branch's files again since
            return Decision("handoff", "rebase finished but the branch still does not merge cleanly")
        if pr_head and pr_head == git.head:
            return Decision("close-rebase", "rebase finished and the open PR already carries it")
        dead = superseded(stages)
        if any(stage == "review" and c["id"] in dead for stage, c in stages):
            return Decision("resume-review", "rebase finished and merge-tree is clean; the review it held resumes")
        return Decision("reverify", "rebase finished and merge-tree is clean")

    rebase = needs_rebase(parent, stages, git)
    if rebase:
        return rebase
    if stages and stages[-1][1]["status"] == "blocked":
        return Decision("skip", "last stage is blocked; its block comment owns it")

    if pr_head:
        # Landed work waits on a human merge; the merge sweep owns it, whatever
        # stage ran last (a re-review after the verify is a normal history).
        return Decision("skip", "PR open")

    if not stages:
        if git.dirty:
            return Decision("handoff", "Worker finished on a dirty tree")
        if git.ahead == 0:
            return Decision("handoff", "Worker finished with no commits")
        if re.search(r"(?m)^\s*Chain:\s*\d+\s*steps", parent.get("description") or ""):
            return Decision("handoff", "chain task")
        return Decision("review", "Worker committed on a clean tree")

    stage, last = stages[-1]
    if stage == "review" and last["status"] == "done":
        # Decide by the diff as much as the label: the label was guessed at
        # intake, and most tasks carry none at all.
        label = pipeline_label(parent)
        if label == "needs-build":
            return Decision("verify", "Reviewer done, needs-build")
        if any(CARGO_PATH.search(path) for path in git.changed):
            return Decision("verify", "Reviewer done, diff touches Rust or data Rust loads")
        if label == "data-only":
            return Decision("handoff", "Reviewer done, data-only with nothing cargo reads")
        return Decision("handoff", "Reviewer done, no label and nothing cargo reads")
    if stage == "verify":
        # Landing and the merge sweep own everything after a verify.
        return Decision("skip", "verify finished; landing owns it")
    return Decision("handoff", f"last stage {stage} ended {last['status']}")


def held_until(comment: str) -> tuple[str, str] | None:
    """(blocker id, "merge" | "pr") for a hold in the release-condition form."""
    m = HELD_UNTIL.match(comment.strip())
    if not m:
        return None
    return m.group(1), "merge" if m.group(2) == "merges" else "pr"


def held_closed(comment: str) -> tuple[str, str] | None:
    """(blocker id, "closed") for a `Held: waiting on <id>` hold.

    That form does not say whether it waits on the merge or on the PR, so it is
    released only when both readings agree: the blocker is done or cancelled.
    Without this, such a hold waits on a Coordinator sweep that rarely gets that far.
    """
    m = LEGACY_HELD.match(comment.strip())
    return (m.group(1), "closed") if m else None


def hold_resolved(blocker: dict | None, kind: str, blocker_pr_open: bool) -> str | None:
    """Why a `Held: until <id> ...` hold is released, or None to keep it."""
    if blocker is None:
        return None
    if blocker["status"] in ("done", "cancelled"):
        return f"{blocker['identifier']} is {blocker['status']}"
    if kind == "pr" and blocker_pr_open:
        return f"{blocker['identifier']} has opened its PR"
    return None


def verify_landed(verify: dict, open_head: str | None, merged_pr: int | None,
                  landed: tuple[str, float] | None) -> str | None:
    """Why an `in_review` Verify has met its goal (cargo-green + PR opened), or None.

    The Architect opens its own PR, and nothing that closes a Verify runs after
    it: the server holds a no-skill task at `in_review` until its branch merges,
    and the operator merges with no Architect run on the task. `landed` is the
    Architect Landing's `{parent}.landed` marker, (head it published, mtime).
    An open PR at that head is not enough alone: a Verify re-dispatched onto a
    head that already has a PR (freshness, a stale red sentinel) starts out in
    exactly that state, with no live run while its cloud build is out. So the
    marker must postdate the Verify, and name the head the PR carries.
    """
    if verify["status"] != "in_review":
        return None
    if merged_pr is not None:
        return f"PR #{merged_pr} for its branch is merged"
    if open_head and landed and landed[0] == open_head and landed[1] > iso_ts(verify["createdAt"]):
        return f"the Architect landed {open_head[:9]} and the open PR carries it"
    return None


def iso_ts(stamp: str) -> float:
    return datetime.fromisoformat(stamp.replace("Z", "+00:00")).timestamp()


def overruled(comments: list[dict], blocker_id: str) -> bool:
    """Whether the Coordinator already re-held this task after we released it.

    The hold names its release condition, so a wrong release means the hold
    was written in the wrong form. The Coordinator's re-hold is the correction;
    releasing again would only buy another Coordinator run to re-hold it.
    """
    *earlier, _latest = sorted(comments, key=lambda c: c["createdAt"]) or [None]
    return any(
        (c.get("body") or "").startswith("Released:") and blocker_id in (c.get("body") or "")
        for c in earlier
    )


def handoff_signature(parent: dict, children: list[dict], git: GitState) -> str:
    newest = max((c["updatedAt"] for c in children), default="")
    return f"{parent['status']}|{git.head}|{git.dirty}|{newest}"


# --------------------------------------------------------------------------- I/O


class Api:
    def __init__(self, dry_run: bool):
        self.base = os.environ.get("PAPERCLIP_API_URL", "http://127.0.0.1:3100").rstrip("/") + "/api"
        self.company = os.environ["PAPERCLIP_COMPANY_ID"]
        self.dry_run = dry_run
        self.headers = {"Content-Type": "application/json"}
        if os.environ.get("PAPERCLIP_API_KEY"):
            self.headers["Authorization"] = f"Bearer {os.environ['PAPERCLIP_API_KEY']}"
        if os.environ.get("PAPERCLIP_RUN_ID"):
            self.headers["X-Paperclip-Run-Id"] = os.environ["PAPERCLIP_RUN_ID"]

    def call(self, method: str, path: str, body: dict | None = None):
        req = urllib.request.Request(
            self.base + path,
            data=None if body is None else json.dumps(body).encode(),
            method=method,
            headers=self.headers,
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read()
            return json.loads(raw) if raw else None

    def get(self, path: str):
        return self.call("GET", path)

    def write(self, method: str, path: str, body: dict, what: str):
        print(("DRY " if self.dry_run else "") + what, flush=True)
        if self.dry_run:
            return None
        return self.call(method, path, body)

    def issues(self, **query) -> list[dict]:
        qs = "&".join(f"{k}={v}" for k, v in query.items())
        return self.get(f"/companies/{self.company}/issues?{qs}")

    def set_status(self, issue: dict, body: dict, comment: str, what: str):
        """Status and its reason in one call; on error, comment first, then PATCH."""
        try:
            self.write("PATCH", f"/issues/{issue['id']}", {**body, "comment": comment}, what)
        except urllib.error.HTTPError:
            self.write("POST", f"/issues/{issue['id']}/comments", {"body": comment}, f"  comment on {issue['identifier']}")
            self.write("PATCH", f"/issues/{issue['id']}", body, f"  retry {what}")


def git(worktree: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(worktree), *args], capture_output=True, text=True, check=True, timeout=60
    ).stdout


def git_state(project: Path, identifier: str) -> GitState:
    wt = project / ".paperclip" / "worktrees" / identifier
    if not wt.is_dir():
        return GitState(exists=False)
    try:
        dirty = bool(git(wt, "status", "--porcelain").strip())
        ahead = int(git(wt, "rev-list", "--count", "origin/main..HEAD").strip() or 0)
        head = git(wt, "rev-parse", "HEAD").strip()
        changed = tuple(git(wt, "diff", "--name-only", "origin/main...HEAD").split())
        merge = subprocess.run(
            ["git", "-C", str(wt), "merge-tree", "--write-tree", "--name-only", "origin/main", "HEAD"],
            capture_output=True, text=True, timeout=60,
        )
    except (subprocess.SubprocessError, ValueError):
        return GitState(exists=False)
    conflicts, deleted = parse_merge_tree(merge.stdout) if merge.returncode == 1 else ((), ())
    split = tuple(p for p in deleted if split_dir(p) and main_has_dir(wt, split_dir(p)))
    return GitState(
        exists=True, dirty=dirty, ahead=ahead, head=head, changed=changed,
        merges_clean=merge.returncode == 0, conflicts=conflicts,
        deleted_on_main=len(split) < len(deleted), split_on_main=split,
    )


def main_has_dir(wt: Path, path: str) -> bool:
    """Whether `origin/main` has a non-empty directory at `path`.

    A plain delete leaves no such path, and `ls-tree` exits 128 on it; that is
    the answer "not split", not an error, and raising here aborts the whole sweep.
    """
    out = subprocess.run(
        ["git", "-C", str(wt), "ls-tree", "--name-only", f"origin/main:{path}"],
        capture_output=True, text=True, timeout=60,
    )
    return out.returncode == 0 and bool(out.stdout.strip())


def split_dir(path: str) -> str | None:
    """The module directory a split of `path` would create: `a/b.rs` -> `a/b`."""
    return path[: -len(".rs")] if path.endswith(".rs") else None


def parse_merge_tree(out: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """(conflicting paths, paths origin/main deleted) from `merge-tree --name-only`.

    The output is the tree id, one conflicted path per line, a blank line, then
    the informational messages.
    """
    head, _, messages = out.partition("\n\n")
    paths = tuple(dict.fromkeys(line for line in head.splitlines()[1:] if line))
    deleted = re.findall(r"CONFLICT \(modify/delete\): (\S+) deleted in origin/main", messages)
    return paths, tuple(dict.fromkeys(deleted))


TRAIN_HEAD = re.compile(r"^train/\d+/([A-Z]+-\d+)$")


def by_head(prs: list[dict], field: str) -> dict[str, object]:
    """{head branch: pr[field]}, with each `train/<n>/<id>` head also keyed as `task/<id>`.

    A train PR carries a task's work cherry-picked onto a stack, so it is that
    task's PR: every lookup here is keyed `task/<id>`, and without the alias a
    train-PR'd task reads as having no PR at all — its holds never release and
    it gets dispatched for work that is already in review. A real `task/<id>`
    head wins over the alias.
    """
    out: dict[str, object] = {pr["headRefName"]: pr[field] for pr in prs}
    for pr in prs:
        m = TRAIN_HEAD.match(pr["headRefName"])
        if m:
            out.setdefault(f"task/{m.group(1)}", pr[field])
    return out


def open_pr_heads(project: Path) -> dict[str, str]:
    """Open PRs as {head branch: head commit}."""
    out = subprocess.run(
        ["gh", "pr", "list", "--state", "open", "--limit", "500", "--json", "headRefName,headRefOid"],
        cwd=project, capture_output=True, text=True, timeout=60, check=True,
    ).stdout
    return by_head(json.loads(out), "headRefOid")


def merged_pr_numbers(project: Path) -> dict[str, int]:
    """Recently merged PRs as {head branch: number}."""
    out = subprocess.run(
        ["gh", "pr", "list", "--state", "merged", "--limit", "300", "--json", "headRefName,number"],
        cwd=project, capture_output=True, text=True, timeout=60, check=True,
    ).stdout
    return by_head(json.loads(out), "number")


def landed_marker(identifier: str) -> tuple[str, float] | None:
    path = VERIFY_DIR / f"{identifier}.landed"
    try:
        return path.read_text().strip(), path.stat().st_mtime
    except OSError:
        return None


def verify_capacity() -> int | None:
    """Verifies that may still be dispatched now; None means unbounded (cloud lane open)."""
    lane = subprocess.run(
        [sys.executable, str(HERE.parent / "architect" / "cloud-pace.py")],
        capture_output=True, text=True, timeout=60,
    ).stdout.strip()
    if lane == "1":
        return None
    try:
        slots = int(Path("/tmp/cargo-sem.slots").read_text().strip())
    except (OSError, ValueError):
        slots = 2
    live = subprocess.run(
        [str(HERE.parent / "architect" / "verify-census.sh")], capture_output=True, text=True, timeout=60,
    ).stdout.split()
    return max(0, 2 * slots - len(live))


def load_state(name: str) -> dict:
    try:
        return json.loads((STATE_DIR / name).read_text())
    except (OSError, ValueError):
        return {}


def save_state(name: str, data: dict, dry_run: bool) -> None:
    if dry_run:
        return
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    (STATE_DIR / name).write_text(json.dumps(data))


# --------------------------------------------------------------------------- actions


def worktree_lines(identifier: str) -> tuple[str, str]:
    return f".paperclip/worktrees/{identifier}", f"task/{identifier}"


def issue_link(identifier: str) -> str:
    return f"[{identifier}](/{identifier.split('-')[0]}/issues/{identifier})"


def create_review(api: Api, agents: dict, parent: dict, git_st: GitState):
    wt, branch = worktree_lines(parent["identifier"])
    label = pipeline_label(parent) or "none"
    files = "\n".join(f"- {p}" for p in git_st.changed) or "- (none)"
    body = (
        f"What: review {branch} against the parent's What/Done-when.\n"
        f"Why: Worker stage complete, commit {git_st.head[:9]}.\n"
        f"Where: worktree {wt} (branch {branch}).\n"
        f"Changed files:\n{files}\n"
        f"Done-when: diff satisfies parent Done-when; Reviewer commits any fixes.\n"
        f"Label: {label}\n\n"
        f"worktree: {wt} (branch {branch})\n"
    )
    api.write(
        "POST",
        f"/companies/{api.company}/issues",
        {
            "title": f"Review: {parent['identifier']} {parent['title']}"[:200],
            "description": body,
            "status": "in_review",
            "priority": parent.get("priority") or "medium",
            "parentId": parent["id"],
            "goalId": parent.get("goalId"),
            "assigneeAgentId": agents["Reviewer"],
            "dedupeKey": "review",
        },
        f"review  {parent['identifier']}: create Review subtask",
    )


def create_verify(api: Api, agents: dict, parent: dict, after: dict, git_st: GitState, dispatch: bool):
    wt, branch = worktree_lines(parent["identifier"])
    held = "" if dispatch else "\nIntended assignee: Architect (held — no verify capacity free)\n"
    where = ", ".join(f"`{p}`" for p in git_st.changed) or "(see branch)"
    body = (
        f"worktree: {wt}\nbranch:   {branch}\n\n"
        "**What** — Run `cargo clippy --all-targets` and `cargo test` against the worktree above, "
        "fix what they report, commit, and open the PR.\n\n"
        f"**Why** — {issue_link(parent['identifier'])}: {parent['title']}. "
        f"{after['title'].split(':')[0].split()[0]} {issue_link(after['identifier'])} is done.\n\n"
        f"**Where** — {where}\n{held}"
    )
    label_ids = [l["id"] for l in parent.get("labels") or [] if l["name"] == "needs-build"]
    api.write(
        "POST",
        f"/companies/{api.company}/issues",
        {
            "title": f"Verify: {parent['identifier']} {parent['title']}"[:200],
            "description": body,
            "status": "in_review" if dispatch else "todo",
            "priority": parent.get("priority") or "medium",
            "parentId": parent["id"],
            "goalId": parent.get("goalId"),
            "assigneeAgentId": agents["Architect"] if dispatch else None,
            "dedupeKey": "verify",
            **({"labelIds": label_ids} if label_ids else {}),
        },
        f"verify  {parent['identifier']}: create Verify subtask ({'dispatched' if dispatch else 'held'})",
    )


def create_rebase(api: Api, agents: dict, parent: dict, stages: list[tuple[str, dict]], git_st: GitState):
    wt, branch = worktree_lines(parent["identifier"])
    paths = rebase_paths(git_st)
    n = rebases_used(stages) + 1
    body = (
        f"Rebase `{branch}` onto `origin/main` and resolve the conflict in "
        + ", ".join(f"`{p}`" for p in paths)
        + ". The implementation on this branch is already complete and reviewed — do not "
        "re-implement it. Leave any `assets/schemas/` conflict on main's side; the Architect "
        "regenerates schemas. "
        + "".join(
            f"`origin/main` split `{p}` into `{split_dir(p)}/`: move this branch's changes to it "
            f"(`git diff origin/main...HEAD -- {p}`) into the matching modules there, then "
            f"`git rm {p}`. "
            for p in git_st.split_on_main
        )
        + "Done-when: `git merge-tree --write-tree origin/main HEAD` exits 0 and the tree is clean.\n\n"
        f"worktree: {project_root()}/{wt} (branch {branch})\n\n"
        f"Rebase task for {parent['identifier']}; Worker rebase: {n}.\n"
    )
    api.write(
        "POST",
        f"/companies/{api.company}/issues",
        {
            "title": f"Rebase {branch} onto origin/main",
            "description": body,
            "status": "todo",
            "priority": parent.get("priority") or "medium",
            "parentId": parent["id"],
            "goalId": parent.get("goalId"),
            "assigneeAgentId": agents["Worker"],
            "dedupeKey": "rebase",
        },
        f"rebase  {parent['identifier']}: create Rebase subtask #{n} ({', '.join(paths)})",
    )


def project_root() -> str:
    return os.environ["PAPERCLIP_PROJECT"].rstrip("/")


def latest_body(api: Api, issue: dict) -> str:
    comments = api.get(f"/issues/{issue['id']}/comments")
    newest = max(comments, key=lambda c: c["createdAt"], default=None)
    return ((newest or {}).get("body") or "").strip()


def retire_superseded(api: Api, agents: dict, stages: list[tuple[str, dict]], rebase: dict, resume: bool):
    """Retire the blocked stages a clean rebase answered.

    A superseded Verify is cancelled: the server dedupes open subtasks on
    `(parentId, dedupeKey)`, so a fresh Verify cannot be created beside it, and
    its block comment describes a branch that no longer exists. A superseded
    Review is resumed instead when `resume` is set -- it never ran.
    """
    dead = superseded(stages)
    for stage, child in stages:
        if child["id"] not in dead:
            continue
        quoted = (latest_body(api, child).splitlines() or ["(no block comment)"])[0]
        if stage == "review" and resume:
            api.set_status(
                child,
                {"status": "in_review", "assigneeAgentId": agents["Reviewer"]},
                f"Released: {rebase['identifier']} rebased the branch and `merge-tree` is clean.\n\n> {quoted}",
                f"review  {child['identifier']}: resume after {rebase['identifier']}",
            )
        else:
            api.set_status(
                child,
                {"status": "cancelled"},
                f"Superseded: {rebase['identifier']} rebased the branch and `merge-tree` is clean; "
                f"a fresh stage runs on the rebased head.\n\n> {quoted}",
                f"{stage:<7} {child['identifier']}: cancel, superseded by {rebase['identifier']}",
            )


# --------------------------------------------------------------------------- sweep


def sweep(api: Api, project: Path) -> None:
    roster = api.get(f"/companies/{api.company}/agents")
    agents = {a["name"]: a["id"] for a in roster}
    worker = next(a for a in roster if a["name"] == "Worker")

    owned = api.issues(status="in_review", assigneeAgentId=agents["Worker"])
    parents = [p for p in owned if not stage_of(p)]
    # A finished rebase's parent may be parked anywhere (a conflict hold blocks
    # it), so it joins the sweep by its child rather than by its own status.
    listed = {p["id"] for p in parents}
    for rebase in owned:
        if finished_rebase(rebase) and rebase.get("parentId") and rebase["parentId"] not in listed:
            listed.add(rebase["parentId"])
            parents.append(api.get(f"/issues/{rebase['parentId']}"))
    # So may a parent whose stage stopped on a conflict: it waits on a rebase
    # nothing else would dispatch.
    for stalled in api.issues(status="blocked"):
        if stage_of(stalled) in ("verify", "review") and stalled.get("parentId") and stalled["parentId"] not in listed:
            listed.add(stalled["parentId"])
            parents.append(api.get(f"/issues/{stalled['parentId']}"))

    def load(parent: dict):
        children = api.issues(parentId=parent["id"])
        if live_stage(ordered_stages(children)):
            return parent, children, None  # a stage is live: no git read needed
        full = api.get(f"/issues/{parent['id']}")
        return full, children, git_state(project, parent["identifier"])

    with concurrent.futures.ThreadPoolExecutor(8) as pool:
        loaded = list(pool.map(load, parents))
    pr_heads = open_pr_heads(project)

    capacity: int | None | str = "unread"  # the probe costs seconds; read it on first use
    slots = ((worker.get("runtimeConfig") or {}).get("heartbeat") or {}).get("maxConcurrentRuns") or 0
    in_flight = len(api.issues(status="todo,in_progress", assigneeAgentId=agents["Worker"]))
    # Rebases take Worker slots ahead of new work: each one is reviewed work a
    # merge away from landing, and the Coordinator promotes only into what is left.
    rebase_slots = max(0, slots - in_flight)
    handed = load_state("handoffs.json")
    handoff: list[dict] = []
    seen: dict[str, str] = {}

    def take_capacity() -> bool:
        nonlocal capacity
        if capacity == "unread":
            capacity = verify_capacity()
        if capacity is None:
            return True
        if capacity > 0:
            capacity -= 1
            return True
        return False

    def hand_off(issue: dict, sig: str, reason: str) -> None:
        seen[issue["id"]] = sig
        if handed.get(issue["id"]) != sig:
            handoff.append({"identifier": issue["identifier"], "reason": reason})

    # Held verifies first: they waited longest for a build slot.
    for held in sorted(
        (v for v in api.issues(status="todo") if stage_of(v) == "verify" and not v.get("assigneeAgentId")),
        key=lambda v: v["createdAt"],
    ):
        body = api.get(f"/issues/{held['id']}").get("description") or ""
        if HELD_VERIFY not in body or not take_capacity():
            continue
        api.set_status(
            held,
            {"status": "in_review", "assigneeAgentId": agents["Architect"]},
            "Dispatching: verify capacity is free (held at creation for lack of a build slot).",
            f"verify  {held['identifier']}: dispatch held verify",
        )

    # Oldest parent first, so a hot file's longest-waiting branch gets the slot.
    for parent, children, git_st in sorted(loaded, key=lambda t: t[0]["createdAt"]):
        if git_st is None:
            continue
        decision = decide(parent, children, git_st, pr_heads.get(f"task/{parent['identifier']}"))
        stages = ordered_stages(children)
        if decision.kind == "review":
            create_review(api, agents, parent, git_st)
        elif decision.kind == "verify":
            review = max((c for c in children if stage_of(c) == "review"), key=lambda c: c["createdAt"])
            create_verify(api, agents, parent, review, git_st, take_capacity())
        elif decision.kind == "rebase":
            if rebase_slots <= 0:
                continue
            for finished in (c for _, c in stages if finished_rebase(c)):  # a `done` one needs nothing
                api.set_status(
                    finished,
                    {"status": "done"},
                    f"Rebase finished, but `origin/main` has since moved on {decision.reason}; "
                    "a fresh rebase follows.",
                    f"rebase  {finished['identifier']}: close (main moved again)",
                )
            create_rebase(api, agents, parent, stages, git_st)
            rebase_slots -= 1
            in_flight += 1
        elif decision.kind in ("reverify", "resume-review", "close-rebase"):
            rebase = unconsumed_rebase(stages)
            follow = {
                "reverify": "The parent needs a fresh verify on the rebased head.",
                "resume-review": "The review it held resumes on the rebased head.",
                "close-rebase": "The open PR's head is this commit, so nothing further is needed here.",
            }[decision.kind]
            retire_superseded(api, agents, stages, rebase, resume=decision.kind == "resume-review")
            if rebase["status"] != "done":
                api.set_status(
                    rebase,
                    {"status": "done"},
                    f"Rebase landed: `merge-tree --write-tree origin/main HEAD` is clean at "
                    f"{git_st.head[:9]}, tree clean. {follow}",
                    f"rebase  {rebase['identifier']}: close ({decision.reason})",
                )
            if decision.kind == "reverify":
                create_verify(api, agents, parent, rebase, git_st, take_capacity())
        elif decision.kind == "handoff":
            hand_off(parent, handoff_signature(parent, children, git_st), decision.reason)

    close_landed_verifies(api, project, pr_heads)
    released = release_holds(api, pr_heads)

    # Promotion needs the Coordinator's contention rules; ask only when it could promote.
    backlog = len(api.issues(status="backlog"))
    refill_state = load_state("refill.json")
    refill = (
        slots > in_flight
        and backlog > 0
        and (released > 0 or time.time() - refill_state.get("at", 0) > REFILL_INTERVAL)
    )

    if handoff or refill:
        note = {
            "at": time.time(),
            "handoff": handoff,
            "refill": refill,
            "freeWorkerSlots": max(0, slots - in_flight),
            "backlog": backlog,
        }
        lines = [f"- {h['identifier']}: {h['reason']}" for h in handoff]
        print(("DRY " if api.dry_run else "") + f"wake    Coordinator: {len(handoff)} hand-off(s), refill={refill}")
        for line in lines:
            print("  " + line)
        if not api.dry_run:
            # Accumulate until the Coordinator takes the file (it renames it on
            # read), so two runs between its wakes cannot drop each other's entries.
            pending = {h["identifier"]: h for h in load_state(HANDOFF_FILE.name).get("handoff", [])}
            pending.update({h["identifier"]: h for h in handoff})
            note["handoff"] = list(pending.values())
            save_state(HANDOFF_FILE.name, note, False)
            api.call(
                "POST",
                f"/agents/{agents['Coordinator']}/wakeup",
                {"source": "automation", "triggerDetail": "callback", "reason": "dispatcher_handoff"},
            )
            if refill:
                save_state("refill.json", {"at": time.time()}, False)
    # Forget tasks that left the hand-off set so a later return re-notifies.
    save_state("handoffs.json", seen, api.dry_run)


def close_landed_verifies(api: Api, project: Path, pr_heads: dict[str, str]) -> None:
    """Close every `in_review` Verify whose PR is open at its landed head, or merged.

    The Coordinator's §Landing closes the Verify for a PR it opens itself; this
    covers the PRs the Architect opens, which no other step ever closed.
    """
    verifies = [v for v in api.issues(status="in_review") if stage_of(v) == "verify" and v.get("parentId")]
    if not verifies:
        return
    merged = merged_pr_numbers(project)
    for verify in verifies:
        identifier = api.get(f"/issues/{verify['parentId']}")["identifier"]
        branch = f"task/{identifier}"
        why = verify_landed(verify, pr_heads.get(branch), merged.get(branch), landed_marker(identifier))
        if why:
            api.set_status(
                verify,
                {"status": "done"},
                f"Verify complete: {why} (`{branch}`).",
                f"verify  {verify['identifier']}: close ({why})",
            )


def release_holds(api: Api, pr_heads: dict[str, str]) -> int:
    """Release `Held: until <id> ...` holds whose condition is met. Returns how many."""
    state = load_state("holds.json")
    if time.time() - state.get("at", 0) < HOLD_SCAN_INTERVAL:
        return 0
    held = [i for i in api.issues(status="blocked") if not i.get("assigneeAgentId")]

    def latest(issue: dict):
        comments = api.get(f"/issues/{issue['id']}/comments")
        newest = max(comments, key=lambda c: c["createdAt"], default=None)
        return issue, (newest or {}).get("body") or "", comments

    with concurrent.futures.ThreadPoolExecutor(8) as pool:
        triples = list(pool.map(latest, held))

    waiting = []
    legacy = 0
    for issue, body, comments in triples:
        parsed = held_until(body) or held_closed(body)
        if parsed and not overruled(comments, parsed[0]):
            waiting.append((issue, body, parsed))
        legacy += body.startswith(LEGACY_HOLD) and not parsed
    if legacy:
        # Holds naming no task stay with the Coordinator.
        print(f"holds   {legacy} in the `Held: waiting on` form with no task named; left to the Coordinator", flush=True)
    blockers: dict[str, dict | None] = {}
    released = 0
    for issue, body, (blocker_id, kind) in waiting:
        if blocker_id not in blockers:
            try:
                blockers[blocker_id] = api.get(f"/issues/{blocker_id}")
            except urllib.error.HTTPError:
                blockers[blocker_id] = None
        why = hold_resolved(blockers[blocker_id], kind, f"task/{blocker_id}" in pr_heads)
        if not why:
            continue
        quoted = body.strip().splitlines()[0]
        api.set_status(
            issue,
            {"status": "backlog"},
            f"Released: {why}.\n\n> {quoted}",
            f"release {issue['identifier']}: {why}",
        )
        released += 1
    save_state("holds.json", {"at": time.time()}, api.dry_run)
    return released


def routine_fire(issue: dict | None, agent_id: str | None) -> bool:
    """Whether the wake's task is an open routine issue assigned to this agent.

    A scheduled fire creates an issue and wakes us on it. Nothing else ever closes
    it, so without this every fire would leave one open `todo` behind.
    """
    return bool(
        issue
        and agent_id
        and issue.get("originKind") == "routine_execution"
        and issue.get("assigneeAgentId") == agent_id
        and issue.get("status") in OPEN
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    project = Path(os.environ["PAPERCLIP_PROJECT"])
    api = Api(args.dry_run)
    sweep(api, project)
    # Closed only after a sweep that returned: a crash leaves the fire's issue open as the trace.
    task_id = os.environ.get("PAPERCLIP_TASK_ID")
    issue = api.get(f"/issues/{task_id}") if task_id else None
    if routine_fire(issue, os.environ.get("PAPERCLIP_AGENT_ID")):
        api.set_status(issue, {"status": "done"}, "Sweep finished.", f"routine {issue['identifier']}: close")
    return 0


if __name__ == "__main__":
    sys.exit(main())
